server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ems-db
        password: root
        username: root
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
